[versions]
agp = "8.12.3"
kotlin = "2.2.20"
kool = "0.18.0"
androidsvg = "1.4"

[libraries]
kool-core = { group = "de.fabmax.kool", name = "kool-core", version.ref = "kool" }
androidsvg = { group = "com.caverock", name = "androidsvg-aar", version.ref = "androidsvg" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

